FORMAT: 1A
HOST: https://known-for-api.cfapps.pez.pivotal.io

# Known For

This is an API to allow implementation of [a simple game][1] based on guessing
what the featured three films for a given actor are. 
 
  [1]: https://github.com/textbook/about/issues/2

## Group People

## Person [/api/person]

The API exposes an endpoint to retrieve a single person from the top 500 most
popular people on [TMDb][2].

  [2]: https://www.themoviedb.org

### Get a random person [GET]

+ Response 200 (application/json)

    + Attributes (Person)

## Mock Person [/mock/api/person]

The API also exposes an endpoint to retrieve a "mock person", using existing
data that is saved in `mock.json`. This doesn't actually touch any external
sites, so is much faster and can even be used for offline testing.

### Get the mock person [GET]

+ Response 200 (application/json)

    + Attributes (Person)

## Group Searches

## Search [/api/search?query]

The API exposes an endpoint to search for a movie by title.

### Search for a movie [GET]

+ Parameters

    + query (string) - The movie title to search for

+ Response 200 (application/json)

    + Attributes (array[string])

## Mock Search [/mock/api/search?query]

The API also exposes an endpoint to retrieve a mock search result, using
existing data that is saved in `search.json`. This doesn't actually touch any
external sites, so is much faster and can even be used for offline testing.

### Mock search for a movie [GET]

+ Parameters

    + query (string) - The movie title to search for

+ Response 200 (application/json)

    + Attributes (array[string])

## Group Configuration

## Config [/api/config]

For debugging and development purposes, the API exposes an endpoint for access
to the stored configuration (see [the TMDb API docs][3]).

  [3]: http://docs.themoviedb.apiary.io/#reference/configuration/get

### Get the current configuration [GET]

+ Response 200 (application/json)

    + Attributes (object)
        + last_update
        + data (object)

## Data Structures

### Person (object)
+ name (required)
+ biography
+ image_url (required)
+ url (required)
+ known_for (array[Movie], required)

### Movie (object)
+ title (required)
+ release_year (number, required)
+ synopsis (required)
+ image_url (required)
+ url (string, required)
